src/DataGg.Web/Areas/Charts/Pages/Buses.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataGg.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DataGg.Web.Areas.Charts.Pages
{
    public class BusesModel : BreadcrumPageModel
    {
        public BusesModel()
        {
            Breadcrums.Add(new Breadcrum("Charts", "/Charts"));
        }

        public void OnGet()
        {
            Breadcrums.Add(new Breadcrum("Buses", $"/Charts/Buses"));
        }
    }
}

src/DataGg.Web/Areas/Charts/Pages/Crime.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataGg.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DataGg.Web.Areas.Charts.Pages
{
    public class Crime : BreadcrumPageModel
    {
        public Crime()
        {
            Breadcrums.Add(new Breadcrum("Charts", "/Charts"));
            Breadcrums.Add(new Breadcrum("Crime", $"/Charts/Crime"));
        }

        public void OnGet()
        {
            
        }
    }
}

src/DataGg.Web/Areas/Charts/Pages/Earnings.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataGg.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DataGg.Web.Areas.Charts.Pages
{
    public class EarningsModel : BreadcrumPageModel
    {
        public EarningsModel()
        {
            Breadcrums.Add(new Breadcrum("Charts", "/Charts"));
            Breadcrums.Add(new Breadcrum("Earnings", $"/Charts/Earnings"));
        }

        public void OnGet()
        {
            
        }
    }
}

src/DataGg.Web/Areas/Charts/Pages/Emissions.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataGg.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DataGg.Web.Areas.Charts.Pages
{
    public class Emission : BreadcrumPageModel
    {
        public Emission()
        {
            Breadcrums.Add(new Breadcrum("Charts", "/Charts"));
            Breadcrums.Add(new Breadcrum("Emission", $"/Charts/Emission"));
        }

        public void OnGet()
        {
            
        }
    }
}

src/DataGg.Web/Areas/Charts/Pages/Employment.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataGg.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DataGg.Web.Areas.Charts.Pages
{
    public class EmploymentModel : BreadcrumPageModel
    {
        public EmploymentModel()
        {
            Breadcrums.Add(new Breadcrum("Charts", "/Charts"));
            Breadcrums.Add(new Breadcrum("Employment", $"/Charts/Employment"));
        }

        public void OnGet()
        {
            
        }
    }
}

src/DataGg.Web/Areas/Charts/Pages/Energy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataGg.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DataGg.Web.Areas.Charts.Pages
{
    public class Energy : BreadcrumPageModel
    {
        public Energy()
        {
            Breadcrums.Add(new Breadcrum("Charts", "/Charts"));
            Breadcrums.Add(new Breadcrum("Energy", $"/Charts/Energy"));
        }

        public void OnGet()
        {
            
        }
    }
}

src/DataGg.Web/Areas/Charts/Pages/FireAndRescue.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataGg.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DataGg.Web.Areas.Charts.Pages
{
    public class FireAndRescueModel : BreadcrumPageModel
    {
        public FireAndRescueModel()
        {
            Breadcrums.Add(new Breadcrum("Charts", "/Charts"));
            Breadcrums.Add(new Breadcrum("Fire and Rescue", $"/Charts/FireAndRescue"));
        }

        public void OnGet()
        {
            
        }
    }
}

src/DataGg.Web/Areas/Charts/Pages/Housing.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataGg.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DataGg.Web.Areas.Charts.Pages
{
    public class Housing : BreadcrumPageModel
    {
        public Housing()
        {
            Breadcrums.Add(new Breadcrum("Charts", "/Charts"));
            Breadcrums.Add(new Breadcrum("Housing", $"/Charts/Housing"));
        }

        public void OnGet()
        {
            
        }
    }
}

src/DataGg.Web/Areas/Charts/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataGg.Web.Models;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DataGg.Web.Areas.Charts.Pages
{
    public class IndexModel : BreadcrumPageModel
    {
        public IndexModel()
        {
            Breadcrums.Add(new Breadcrum("Charts", "/Charts"));

        }
        public async void OnGetAsync(string stub)
        {
            Breadcrums.Add(new Breadcrum(stub, $"/Charts/{stub}"));
        }

    }
}

src/DataGg.Web/Areas/Charts/Pages/Tourism.cshtml.cs
using DataGg.Web.Models;

namespace DataGg.Web.Areas.Charts.Pages
{
    public class Tourism : BreadcrumPageModel
    {
        public Tourism() {
            Breadcrums.Add(new Breadcrum("Charts", "/Charts"));
            Breadcrums.Add(new Breadcrum("Tourism", "/Charts/Tourism"));
        }

        public void OnGet()
        {
            
        }
    }
}

src/DataGg.Web/ViewComponents/BusUsageChartViewComponent.cs
using DataGg.Core.Types;
using DataGg.Web.Services;
using Highsoft.Web.Mvc.Charts;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace DataGg.Web.ViewComponents
{
    public class BusUsageChartViewComponent : ViewComponent
    {

        private readonly CacheManager _cacheManager;

        public BusUsageChartViewComponent(CacheManager cacheManager)
        {

            _cacheManager = cacheManager;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var dataCache = await _cacheManager.DataCache.Get();

            var model = new BusUsageChartViewComponentModel();

            var culture = CultureInfo.GetCultureInfo("en-GB");

            // there are words here saying why its 13 and not 12
            // https://docs.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo.abbreviatedmonthnames?view=net-5.0
            // it's rubbish, but there are words
            var monthNames = culture.DateTimeFormat.AbbreviatedMonthNames.Take(12);

            model.BusUsage = new List<AreaSeriesData>();
            model.BusUsageLabels = new List<string>();

            foreach(var year in dataCache.BusUsage.OrderBy(y=>y.Year))
            {
                foreach(var m in monthNames)
                {
                    model.BusUsageLabels.Add($"{m} {year.Year}");
                }

                model.BusUsage.Add(new AreaSeriesData { Y = year.January });
                model.BusUsage.Add(new AreaSeriesData { Y = year.February });
                model.BusUsage.Add(new AreaSeriesData { Y = year.March});
                model.BusUsage.Add(new AreaSeriesData { Y = year.April });
                model.BusUsage.Add(new AreaSeriesData { Y = year.May });
                model.BusUsage.Add(new AreaSeriesData { Y = year.June });
                model.BusUsage.Add(new AreaSeriesData { Y = year.July });
                model.BusUsage.Add(new AreaSeriesData { Y = year.August });
                model.BusUsage.Add(new AreaSeriesData { Y = year.September });
                model.BusUsage.Add(new AreaSeriesData { Y = year.October });
                model.BusUsage.Add(new AreaSeriesData { Y = year.November });
                model.BusUsage.Add(new AreaSeriesData { Y = year.December });
            }

            return View(model);
        }
    }

    public class BusUsageChartViewComponentModel
    {
        public List<AreaSeriesData> BusUsage { get; set; }
        public List<string> BusUsageLabels { get; set; }
    }
}

src/DataGg.Web/ViewComponents/EarningsSexChartViewComponent.cs
using DataGg.Core.Types;
using DataGg.Web.Models;
using DataGg.Web.Services;
using Highsoft.Web.Mvc.Charts;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace DataGg.Web.ViewComponents
{
    public class EarningsSexChartViewComponent : ViewComponent
    {

        private readonly CacheManager _cacheManager;

        public EarningsSexChartViewComponent(CacheManager cacheManager)
        {

            _cacheManager = cacheManager;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var dataCache = await _cacheManager.DataCache.Get();

            var model = new LineChartViewModel() { TitleText = "Sex", YAxisTitleText = "Sex", Id = "chartSex" };

            var maleSet = new List<LineSeriesData>();
            var femaleSet = new List<LineSeriesData>();


            model.Data = new List<Series>
            {
                new LineSeries { Name = "Male", Data = maleSet },
                new LineSeries { Name = "Female", Data = femaleSet },

            };
            
            model.Labels = new List<string>();

            var culture = CultureInfo.GetCultureInfo("en-GB");
            foreach (var qtr in dataCache.EarningsSex.OrderBy(y => DateTime.Parse(y.Date, culture)))
            {
                maleSet.Add(new LineSeriesData { Y = qtr.Male });
                femaleSet.Add(new LineSeriesData { Y = qtr.Female });

                
                model.Labels.Add($"{qtr.Date}");

            }

            return View(model);
        }
    }
}

src/DataGg.Web/ViewComponents/GenericAreaChartViewComponent.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using DataGg.Core.Attributes;
using DataGg.Core.Extensions;
using DataGg.Web.Models;
using DataGg.Web.Services;
using Highsoft.Web.Mvc.Charts;
using Microsoft.AspNetCore.Mvc;

namespace DataGg.Web.ViewComponents;

public class GenericAreaChartViewComponent : ViewComponent
{
    private readonly CacheManager _cacheManager;

    public GenericAreaChartViewComponent(CacheManager cacheManager)
    {
        _cacheManager = cacheManager;
    }

    public async Task<IViewComponentResult> InvokeAsync(string id, string title, string yAxisLabel, Type type, string groupName = "")
    {
        var dataCache = await _cacheManager.DataCache.Get();

        var model = new AreaChartViewModel
        {
            TitleText = title,
            YAxisTitleText = yAxisLabel,
            Id = id,
            Data = new List<Series>()
        };

        var chartingData = dataCache.GetChartingDataForType(type);
        var columns = chartingData.ColumnsFiltered(groupName);

        var counters = new double?[columns.Length];

        for (var i = 0; i < columns.Length; i++)
        {
            var columnSeries = columns[i];
            model.Data.Add(new AreaSeries
            {
                Name = columnSeries.DisplayName,
                ShowInLegend = true,
                Data = new List<AreaSeriesData>()
            });


            counters[i] = 100;
        }

        model.Labels = new List<string>();

        foreach (var row in chartingData.OrderedItems)
        {
            var hasData = false;

            for (var i = 0; i < columns.Length; i++)
            {
                var column = columns[i];

                var value = column.PropertyInfo.GetValueAsDouble(row);

                if (value.HasValue)
                {
                    hasData = true;

                    if (column.CalcMethod == CalcMethod.PercentChange)
                    {
                        var fract = counters[i] / 100D * value;
                        value = fract + counters[i];
                    }

                    ((AreaSeries)model.Data[i]).Data.Add(new AreaSeriesData
                    {
                        Y = value
                    });

                    counters[i] = value ?? 100;
                }
            }

            if (hasData)
            {
                model.Labels.Add(string.Format("{0: " + chartingData.GroupingColumn.Format + "}",
                    chartingData.GroupingColumn.PropertyInfo.GetValue(row)));
            }
        }

        return View(model);
    }
}

src/DataGg.Web/ViewComponents/OverseasAidChartViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataGg.Web.Models;
using DataGg.Web.Services;
using Highsoft.Web.Mvc.Charts;
using Microsoft.AspNetCore.Mvc;

namespace DataGg.Web.ViewComponents;

public class OverseasAidChartViewComponent : ViewComponent
{
    private readonly CacheManager _cacheManager;

    public OverseasAidChartViewComponent(CacheManager cacheManager)
    {
        _cacheManager = cacheManager;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var dataCache = await _cacheManager.DataCache.Get();

        var model = new AreaChartViewModel()
        {
            TitleText = "Overseas Aid", YAxisTitleText = "Overseas Aid", Id = "chartOverseasAid",
            Stacking = PlotOptionsAreaStacking.Normal
        };
        
        var africaAid = new List<AreaSeriesData>();
        var africaEmergency = new List<AreaSeriesData>();
        
        var europeAid = new List<AreaSeriesData>();
        var europeEmergency = new List<AreaSeriesData>();
        
        var indianSubContinentAid = new List<AreaSeriesData>();
        var indianSubContinentEmergency = new List<AreaSeriesData>();
             
        var latinAmericaCaribbeanAid = new List<AreaSeriesData>();
        var latinAmericaCaribbeanEmergency = new List<AreaSeriesData>();   
             
        var middleEastAid = new List<AreaSeriesData>();
        var middleEastEmergency = new List<AreaSeriesData>();
        
        var otherAsiaPacificAid = new List<AreaSeriesData>();
        var otherAsiaPacificEmergency = new List<AreaSeriesData>();
        
        model.Data = new List<Series>
        {
            new AreaSeries { Name = "Africa Aid", Data = africaAid },
            new AreaSeries { Name = "Africa Emergency Relief", Data = africaEmergency },
            
            new AreaSeries { Name = "Europe Aid", Data = europeAid },
            new AreaSeries { Name = "Europe Emergency Relief", Data = europeEmergency },            
            
            new AreaSeries { Name = "Indian Sub-Continent Aid", Data = indianSubContinentAid },
            new AreaSeries { Name = "Indian Sub-Continent Emergency Relief", Data = indianSubContinentEmergency },
            
            new AreaSeries { Name = "Latin America & Caribbean Aid", Data = latinAmericaCaribbeanAid },
            new AreaSeries { Name = "Latin America & Caribbean Emergency Relief", Data = latinAmericaCaribbeanEmergency },
            
            new AreaSeries { Name = "Other Asia & Pacific Aid", Data = otherAsiaPacificAid },
            new AreaSeries { Name = "Other Asia & Pacific Emergency Relief", Data = otherAsiaPacificEmergency },
            
            new AreaSeries { Name = "Middle East Aid", Data = middleEastAid },
            new AreaSeries { Name = "Middle East Emergency Relief", Data = middleEastEmergency },

        };
        model.Labels = new List<string>();

        foreach (var qtr in dataCache.OverseasContributions.OrderBy(y => y.Year))
        {

            africaAid.Add(new AreaSeriesData
            {
                Y = qtr.AfricaAid
            });

            africaEmergency.Add(new AreaSeriesData
            {
                Y = qtr.AfricaEmergencyRelief
            });
            
            europeAid.Add(new AreaSeriesData
            {
                Y = qtr.EuropeAid
            });

            europeEmergency.Add(new AreaSeriesData
            {
                Y = qtr.EuropeEmergencyRelief
            });
            
            indianSubContinentAid.Add(new AreaSeriesData
            {
                Y = qtr.IndianSubContinentAid
            });

            indianSubContinentEmergency.Add(new AreaSeriesData
            {
                Y = qtr.IndianSubContinentEmergencyRelief
            });
            
            latinAmericaCaribbeanAid.Add(new AreaSeriesData
            {
                Y = qtr.LatinAmericaAndCaribbeanAid
            });

            latinAmericaCaribbeanEmergency.Add(new AreaSeriesData
            {
                Y = qtr.LatinAmericaAndCaribbeanEmergencyRelief
            });
            
            otherAsiaPacificAid.Add(new AreaSeriesData
            {
                Y = qtr.OtherAsiaAndPacificAid
            });

            otherAsiaPacificEmergency.Add(new AreaSeriesData
            {
                Y = qtr.OtherAsiaAndPacificEmergencyRelief
            });
            
            middleEastAid.Add(new AreaSeriesData
            {
                Y = qtr.MiddleEastAid
            });
            
            middleEastEmergency.Add(new AreaSeriesData
            {
                Y = qtr.MiddleEastEmergencyRelief
            });



            model.Labels.Add($"{qtr.Year}");
        }

        return View(model);
    }
}

src/DataGg.Web/Areas/Charts/Pages/Buses.cshtml
@page "/Charts/Buses"
@{
    ViewData["Title"] = "Buses";
}


@model DataGg.Web.Areas.Charts.Pages.BusesModel


@await Component.InvokeAsync("BusUsageChart", new { })

src/DataGg.Web/Areas/Charts/Pages/Crime.cshtml
@page "/Charts/Crime"

@{
    ViewData["Title"] = "Crime";
}


@model DataGg.Web.Areas.Charts.Pages.Crime

<!-- Nav tabs -->
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="prison-pop-tab" data-toggle="tab" href="#prison-pop" role="tab" aria-controls="prison-pop" aria-selected="true">Prison</a>
    </li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div class="tab-pane active" id="prison-pop" role="tabpanel" aria-labelledby="prison-pop-tab">
        @await Component.InvokeAsync("PrisonPopulationChart", new { })
    </div>
</div>

src/DataGg.Web/Areas/Charts/Pages/Earnings.cshtml
@page "/Charts/Earnings"

@{
    ViewData["Title"] = "Earnings";
}


@model DataGg.Web.Areas.Charts.Pages.EarningsModel


<!-- Nav tabs -->
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="sex-tab" data-toggle="tab" href="#sex" role="tab" aria-controls="sex" aria-selected="true">Sex</a>
    </li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div class="tab-pane active" id="sex" role="tabpanel" aria-labelledby="sex-tab">
        @await Component.InvokeAsync("EarningsSexChart", new { })
    </div>
</div>

src/DataGg.Web/Areas/Charts/Pages/Emissions.cshtml
@page "/Charts/Emissions"

@model DataGg.Web.Areas.Charts.Pages.Emission

@{
    ViewData["Title"] = "Emissions";
}

<!-- Nav tabs -->
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="sources-tab" data-toggle="tab" href="#sources" role="tab" aria-controls="sources" aria-selected="true">Sources</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="types-tab" data-toggle="tab" href="#types" role="tab" aria-controls="types" aria-selected="false">Types</a>
    </li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div class="tab-pane active" id="sources" role="tabpanel" aria-labelledby="sources-tab">
        @await Component.InvokeAsync("EmissionSourcesChart", new { })
    </div>
    <div class="tab-pane" id="types" role="tabpanel" aria-labelledby="types-tab">
        @await Component.InvokeAsync("EmissionTypesChart", new { })
    </div>
</div>

src/DataGg.Web/Areas/Charts/Pages/Employment.cshtml
@page "/Charts/Employment"

@{
    ViewData["Title"] = "Employment";
}


@model DataGg.Web.Areas.Charts.Pages.EmploymentModel


<!-- Nav tabs -->
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="totals-tab" data-toggle="tab" href="#totals" role="tab" aria-controls="totals" aria-selected="true">Totals</a>
    </li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div class="tab-pane active" id="totals" role="tabpanel" aria-labelledby="totals-tab">
        @await Component.InvokeAsync("EmploymentTotalsChart", new { })
    </div>
</div>

src/DataGg.Web/Areas/Charts/Pages/Energy.cshtml
@page "/Charts/Energy"

@model DataGg.Web.Areas.Charts.Pages.Energy
@{
    ViewData["Title"] = "Energy";
}


<!-- Nav tabs -->
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="consumption-tab" data-toggle="tab" href="#consumption" role="tab" aria-controls="consumption" aria-selected="true">Consumption</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="importedVsGenerated-tab" data-toggle="tab" href="#importedVsGenerated" role="tab" aria-controls="importedVsGenerated" aria-selected="false">Imported vs Generated</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="renewable-tab" data-toggle="tab" href="#renewable" role="tab" aria-controls="renewable" aria-selected="false">Renewable</a>
    </li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div class="tab-pane active" id="consumption" role="tabpanel" aria-labelledby="consumption-tab">
        @await Component.InvokeAsync("EnergyConsumptionChart", new { })
    </div>
    <div class="tab-pane" id="importedVsGenerated" role="tabpanel" aria-labelledby="importedVsGenerated-tab">
        @await Component.InvokeAsync("EnergyImportedVsGeneratedChart", new { })
    </div>

    <div class="tab-pane" id="renewable" role="tabpanel" aria-labelledby="renewable-tab">
        @await Component.InvokeAsync("EnergyRenewableChart", new { })
    </div>
</div>

src/DataGg.Web/Areas/Charts/Pages/FireAndRescue.cshtml
@page "/Charts/FireAndRescue"

@{
    ViewData["Title"] = "Fire and Rescue";
}


@model DataGg.Web.Areas.Charts.Pages.FireAndRescueModel


<!-- Nav tabs -->
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="attendances-tab" data-toggle="tab" 
           href="#attendances" role="tab" aria-controls="attendances" aria-selected="true">Attendances</a>
    </li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div class="tab-pane active" id="attendances" role="tabpanel" aria-labelledby="attendances-tab">
        @await Component.InvokeAsync("FireAndRescueAttendancesChart", new { })
    </div>
</div>

src/DataGg.Web/Areas/Charts/Pages/Housing.cshtml
@page "/Charts/Housing"

@using DataGg.Core.Guernsey.Houses
@model DataGg.Web.Areas.Charts.Pages.Housing
@{
    ViewData["Title"] = "Housing";
}

<!-- Nav tabs -->
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="mean-avg-tab" data-toggle="tab" href="#mean-avg" role="tab" aria-controls="mean-avg" aria-selected="true">Mean Average</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="transactions-tab" data-toggle="tab" href="#transactions" role="tab" aria-controls="transactions" aria-selected="false">Transactions</a>
    </li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div class="tab-pane active" id="mean-avg" role="tabpanel" aria-labelledby="mean-avg-tab">

        @await Component.InvokeAsync("GenericAreaChart", new
        {
            id = "chartMeanAvg", Title = "Mean Average", YAxisLabel = "Mean Average",
            Type = typeof(LocalPrices), GroupName = "Mean"
        })
    </div>
    <div class="tab-pane" id="transactions" role="tabpanel" aria-labelledby="transactions-tab">

        @await Component.InvokeAsync("GenericAreaChart", new
        {
            id = "chartTransactions", Title = "Transactions", YAxisLabel = "Transaction Count",
            Type = typeof(LocalPrices), GroupName = "Transactions"
        })
    </div>
</div>

src/DataGg.Web/Areas/Charts/Pages/Index.cshtml
@page "/Charts/{Stub}"
@model DataGg.Web.Areas.Charts.Pages.IndexModel
@{
}

src/DataGg.Web/Areas/Charts/Pages/Inflation.cshtml
@page "/Charts/Inflation"
@using DataGg.Core.Guernsey.Inflation
@using Highsoft.Web.Mvc.Charts
@model DataGg.Web.Areas.Charts.Pages.Inflation
@{
    ViewData["Title"] = "Inflation";
}

<!-- Nav tabs -->
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="changes-tab" data-toggle="tab" href="#changes" role="tab" aria-controls="changes" aria-selected="true">Changes</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="rpi-tab" data-toggle="tab" href="#rpi" role="tab" aria-controls="rpi" aria-selected="false">RPI</a>
    </li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div class="tab-pane active" id="changes" role="tabpanel" aria-labelledby="changes-tab">
        @await Component.InvokeAsync("GenericAreaChart", new
        {
            id = "chartChanges", Title = "Cumulative RPI Changes Quarterly", YAxisLabel = "% Change",
            Type = typeof(Changes), GroupName = ""
        })
    </div>

    <div class="tab-pane" id="rpi" role="tabpanel" aria-labelledby="rpi-tab">
        @await Component.InvokeAsync("GroupChangesAreaChart", new { })
    </div>
</div>

src/DataGg.Web/Areas/Charts/Pages/OverseasAid.cshtml
@page "/Charts/OverseasAid"
@model DataGg.Web.Areas.Charts.Pages.OverseasAidModel
@{
    ViewData["Title"] = "Overseas Aid";
}


@await Component.InvokeAsync("OverseasAidChart", new { })